services:

  java-mystery-number-game:
    container_name: java-mystery-number-game
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    command: sleep infinity
    volumes:
      - ../..:/app
    networks:
      - my_network
    # cpus: 1
    # mem_limit: 2G

networks:
  my_network:
    name: my_network
